### ISSUE TITLE
portrait photos are sent landscape

### ISSUE THREAD

**Issue by legacychimera247** [blacksailer/depecher#49]
well the title pretty much explains it all...portrait photos are sent landscape...sailorgram was doing the same...don't know if could be solved at this time but thought about reporting...

**Comment by paolomi** [comment]
@legacychimera247 now it's fixed in 0.5, please verify it (and close this issue)

**Comment by legacychimera247** [comment]
checked and it's not fixed, but checking on the pc sometime ago i noticed that photos are sent right, it's just sailfish (because this bug it's present in every sf telegram app) displaying photos wrong...

**Comment by paolomi** [comment]
@legacychimera247 
some versions ago this bug happened to me too, but now (0.5.2) i can't reproduce it anymore.

**Comment by legacychimera247** [comment]
i just noticed that photos are sent correctly, simply it's just depecher (but in reality every sailfish client) that displays portrait photos from camera in landscape, even if as stated photos are sent and received correctly...
